#!user/bin/env groovy
@Library('jenkins-shared-library')_

pipeline {
    agent any
    tools {
        maven "maven"
    }
    environment {
        IMAGE_VERSION = 'micro-1.0.0'
    }

    parameters {
        string(name: 'NexusHost', defaultValue: '0.0.0.0', description: 'Nexus Host where to deploy images and jars')
        string(name: 'DockerRepositoryPort', defaultValue: '', description: 'Docker Hosted Repository Port')
    }

    stages {

        stage("build jar") {
            steps {
                script {
                    buildJar 'product-service'
                }
            }
        }
        stage("build and push Image") {
            steps {
                script {
                    dockerLogin "${NexusHost}", "${DockerRepositoryPort}"
                    dockerBuild "${NexusHost}", "${DockerRepositoryPort}", 'product-service', "${IMAGE_VERSION}", 'services/product-service/'
                    dockerPush "${NexusHost}", "${DockerRepositoryPort}", 'product-service', "${IMAGE_VERSION}"
                }
            }
        }

    }
}