spring:
  application:
    name: config-service
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/abdessamadabidar/config-repository
          default-label: main
          username: abdessamadabidar
          password: ${GITHUB_PUBLIC_ACCESS_TOKEN}
          force-pull: true
          skip-ssl-validation: true
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true