#!user/bin/env groovy
@Library('jenkins-shared-library')_

pipeline {
    agent any
    tools {
        maven "maven"
    }
    environment {
        IMAGE_VERSION = 'micro-1.0.0'
    }

    stages {

        stage("build jar") {
            steps {
                script {
                    buildJar 'payment-service'
                }
            }
        }
        stage("build and push Image") {
            steps {
                script {
                    dockerLogin()
                    dockerBuild 'abdessamadabidar/payment-service', "${IMAGE_VERSION}", 'services/payment-service/'
                    dockerPush 'abdessamadabidar/payment-service', "${IMAGE_VERSION}"
                }
            }
        }

    }
}