# Deployment

applicationName: order-service-db

applicationReplicas: 1

imageName: postgres

imageVersion: latest

containerPort: 5432

imgPullPolicy: IfNotPresent

containerSecretEnvVars:
  - name: POSTGRES_USER
    secretName: order-service-db-secret
    key: postgres-username
  - name: POSTGRES_PASSWORD
    secretName: order-service-db-secret
    key: postgres-password
  - name: POSTGRES_DB
    secretName: order-service-db-secret
    key: postgres-db

# Service

serviceType: ClusterIP

serviceName: order-service-db

servicePort: 5432


# Secret

postgresUsername: abdessamad

postgresPassword: abdessamadpwd

databaseName: order_service_db


