#!user/bin/env groovy
@Library('jenkins-shared-library')_

pipeline {
    agent any
    tools {
        maven "maven"
    }
    environment {
        IMAGE_VERSION = 'micro-1.0.0'
    }

    parameters {
        string(name: 'NexusHost', defaultValue: '0.0.0.0', description: 'Nexus Host where to deploy images and jars')
        string(name: 'DockerRepositoryPort', defaultValue: '', description: 'Docker Hosted Repository Port')
        string(name: 'AnsibleHost', defaultValue: '0.0.0.0', description: 'Ansible Host where execute deployment tasks')
    }
    stages {

//        stage("build jar") {
//            steps {
//                script {
//                    buildJar 'customer-service'
//                }
//            }
//        }
//
//        stage("build and push Image") {
//            steps {
//                script {
//                    dockerLogin "${NexusHost}", "${DockerRepositoryPort}"
//                    dockerBuild "${NexusHost}", "${DockerRepositoryPort}", 'customer-service', "${IMAGE_VERSION}", 'services/customer-service/'
//                    dockerPush "${NexusHost}", "${DockerRepositoryPort}", 'customer-service', "${IMAGE_VERSION}"
//                }
//            }
//        }

        stage("Copy Resources files to Ansible server") {
            steps {
                script {
                    copy "${AnsibleHost}"
                }
            }
        }

        stage ("Execute Ansible playbook") {
            steps {
                script {
                    deploy "${AnsibleHost}", "${NexusHost}"
                }
            }
        }

    }

    post {
        always {
            cleanWs()
        }
    }
}