#!user/bin/env groovy
@Library('jenkins-shared-library')_

pipeline {
    agent {
        label 'any'
        customWorkspace '/var/jenkins_home/workspace/shopino-microservices/services'
    }
    tools {
        maven "maven"
    }
    environment {
        IMAGE_VERSION = 'micro-1.0.0'
    }

    stages {

        stage("build jar") {
            steps {
                script {
                    buildJar 'customer-service'
                }
            }
        }

        stage("build and push Image") {
            steps {
                script {
                    dockerLogin()
                    dockerBuild 'abdessamadabidar/customer-service', "${IMAGE_VERSION}", 'services/customer-service/'
                    dockerPush 'abdessamadabidar/customer-service', "${IMAGE_VERSION}"
                }
            }
        }

    }
}