spring:
  config:
    import: optional:configserver:localhost:8888

  application:
    name: payment-service

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: payment-topic

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

  sql:
    init:
      mode: never

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service_db
    username: abdessamad
    password: abdessamadabidar@xyz
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
server:
  port: 8084


