#!user/bin/env groovy
@Library('jenkins-shared-library')_

pipeline {
    agent {
        label 'master'
        customWorkspace '/var/jenkins_home/workspace/shopino-microservices/services/'
    }
    tools {
        maven "maven"
    }

    environment {
        IMAGE_VERSION = 'micro-1.0.0'
    }

    stages {

        stage("build Jar") {
            steps {
                script {
                    buildJar 'config-service'
                }
            }
        }

        stage("build and push Image") {
            steps {
                script {
                    dockerLogin()
                    dockerBuild 'abdessamadabidar/config-service', "${IMAGE_VERSION}", 'services/config-service/'
                    dockerPush 'abdessamadabidar/config-service', "${IMAGE_VERSION}"
                }
            }
        }

    }
}