#!user/bin/env groovy


@Library('jenkins-shared-library')_

pipeline {
    agent any
    tools {
        maven "maven"
    }

    stages {

        stage("build jar") {
            steps {
                script {
                    buildJar()
                }
            }
        }


    }
}