#!user/bin/env groovy
@Library('jenkins-shared-library')_

pipeline {
    agent any
    tools {
        maven "maven"
    }
    environment {
        IMAGE_VERSION = 'micro-1.0.0'
        NEXUS_HOST = 'square-flea-eminently.ngrok-free.app'
    }
    parameters {
        string(name: 'AnsibleHost', defaultValue: '0.0.0.0', description: 'Ansible Host where execute deployment tasks')
    }

    stages {

        stage("build jar") {
            steps {
                script {
                    buildJar 'notification-service'
                }
            }
        }

        stage("build and push Image") {
            steps {
                script {
                    dockerLogin "${NEXUS_HOST}"
                    dockerBuild "${NEXUS_HOST}", 'notification-service', "${IMAGE_VERSION}", 'services/notification-service/'
                    dockerPush "${NEXUS_HOST}", 'notification-service', "${IMAGE_VERSION}"
                }
            }
        }

    }

    post {
        always {
            cleanWs()
        }
    }
}