#!user/bin/env groovy
@Library('jenkins-shared-library')_

pipeline {
    agent any
    tools {
        maven "maven"
    }
    environment {
        IMAGE_VERSION = 'micro-1.0.0'
    }

    parameters {
        string(name: 'NexusHost', defaultValue: '0.0.0.0', description: 'Nexus Host where to deploy images and jars')
        string(name: 'DockerRepositoryPort', defaultValue: '', description: 'Docker Hosted Repository Port')
    }

    stages {

        stage("build jar") {
            steps {
                script {
                    buildJar 'discovery-service'
                }
            }
        }

        stage("build and push Image") {
            steps {
                script {
                    dockerLogin "${NexusHost}", "${DockerRepositoryPort}"
                    dockerBuild "${NexusHost}", "${DockerRepositoryPort}", 'discovery-service', "${IMAGE_VERSION}", 'services/discovery-service/'
                    dockerPush "${NexusHost}", "${DockerRepositoryPort}", 'discovery-service', "${IMAGE_VERSION}"
                }
            }
        }

    }
    post {
        always {
            cleanWs()
        }
    }
}