apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.applicationName }}-secret"
type: Opaque
data:
  github-public-access-token: {{ .Values.githubPublicAccessToken | quote | b64enc }}
  postgres-username: {{ .Values.postgresUsername | default "" | b64enc }}
  postgres-password: {{ .Values.postgresPassword | default "" | b64enc }}
  postgres-db: {{ .Values.databaseName | default "" | b64enc }}
  mongo-username: {{ .Values.mongoUsername | default "" | b64enc }}
  mongo-password: {{ .Values.mongoPassword | default "" | b64enc }}
  mongo-root-username: {{ .Values.mongoRootUsername | default "" | b64enc }}
  mongo-root-password: {{ .Values.mongoRootPassword | default "" | b64enc }}
  mongo-db: {{ .Values.mongoDatabaseName | default "" | b64enc }}