apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      {{- if eq .Values.serviceType "NodePort" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}

