---
- name: Deploy Helm chart and helmfile to EC2
  hosts: aws_ec2
  become: true
  tasks:
    - name: Creates a destination directory
      ansible.builtin.file:
        path: ~/helm
        state: directory

    - name: Copy the Nexus DNS Script to EC2
      ansible.builtin.copy:
        src: ~/nexus_dns.sh
        dest: ~/nexus_dns.sh
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Run Helm commands on EC2
      ansible.builtin.shell: |
        ./nexus_dns.sh '1.1.1.1'
      args:

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ~/helm
        dest: ~/helm
        owner: ubuntu
        group: ubuntu
        mode: '0644'

