---
- name: Deploy Helm chart and helmfile to EC2
  hosts: aws_ec2
  become: true
  tasks:
    - name: Creates a destination directory
      ansible.builtin.file:
        path: /home/ubuntu/helm
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy the Nexus DNS Script to EC2
      ansible.builtin.copy:
        src: ~/nexushost.sh
        dest: /home/ubuntu/nexushost.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy Helm directory to EC2
      ansible.builtin.copy:
        src: ~/helm/
        dest: /home/ubuntu/helm/
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        directory_mode: yes

    - name: Run Nexus DNS Script on EC2
      ansible.builtin.shell: |
        ./nexus_dns.sh '{{ NexusHost }}'
      args:
        chdir: /home/ubuntu
      become: true

    - name: Create pull image secret
      ansible.builtin.shell: |
        kubectl create secret docker-registry regcred --docker-server=nexus.local:8083 --docker-username=abdessamadabidar --docker-password=root --docker-email=abdessamad.abidar@outlook.com
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config

    - name: Run helm chart on EC2 server
      ansible.builtin.shell: |
        export GITHUB_PUBLIC_ACCESS_TOKEN="{{ GITHUB_PUBLIC_ACCESS_TOKEN }}"
        cd /home/ubuntu/helm && helmfile sync
      become: true
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
        GITHUB_PUBLIC_ACCESS_TOKEN: "{{ GITHUB_PUBLIC_ACCESS_TOKEN }}"