---
- name: Deploy Helm chart and helmfile to EC2
  hosts: aws_ec2
  become: true
  tasks:
    - name: Creates a destination directory
      ansible.builtin.file:
        path: /home/ubuntu/helm
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy the Nexus DNS Script to EC2
      ansible.builtin.copy:
        src: ~/nexus_dns.sh
        dest: /home/ubuntu/nexus_dns.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy Helm directory to EC2
      ansible.builtin.copy:
        src: ~/helm/
        dest: /home/ubuntu/helm/
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        directory_mode: yes

    - name: Run Nexus DNS Script on EC2
      ansible.builtin.shell: |
        ./nexus_dns.sh '{{ NexusHost }}'
      args:
        chdir: /home/ubuntu
      become: true

    - name: Run helm chart on EC2 server
      ansible.builtin.shell: |
        cd /home/ubuntu/helm && helmfile sync
      become: true
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
