---
- name: Deploy Helm chart and helmfile to EC2
  hosts: aws_ec2
  become: true
  tasks:
    - name: Creates a destination directory
      ansible.builtin.file:
        path: /home/ubuntu/helm
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy the Nexus DNS Script to EC2
      ansible.builtin.copy:
        src: /home/abdessamadabidar/nexus_dns.sh
        dest: /home/ubuntu/nexus_dns.sh
        remote_src: true
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Run Nexus DNS Script on EC2
      ansible.builtin.shell: |
        ./nexus_dns.sh '1.1.1.1'
      become_user: ubuntu

    - name: Copy Helm directory to EC2
      ansible.builtin.copy:
        src: /home/abdessamadabidar/helm/
        dest: /home/ubuntu/helm/
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        recursive: yes