spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      database: notifications_service_db
      username: abdessamad
      password: abdessamadpwd
      authentication-database: admin

  config:
    import: optional:configserver:localhost:8888

  application:
    name: notification-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

server:
  port: 8085



