spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notifications
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "*"
        "[spring.json.type.mapping]": orderConfirmationNotification:org.shared.OrderConfirmationNotification,paymentRequestNotification:org.shared.PaymentRequestNotification
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notifications_service_db
      username: abdessamad
      password: abdessamadpwd
      authentication-database: admin

  config:
    import: optional:configserver:localhost:8888

  application:
    name: notification-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

server:
  port: 8085



