spring:
  config:
    import: optional:configserver:localhost:8888

  application:
    name: notification-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service

server:
  port: 8085



