#!user/bin/env groovy
@Library('jenkins-shared-library')_

pipeline {
    agent any
    tools {
        maven "maven"
    }


    stages {

        stage("install module") {
            steps {
                script {
                    install 'common'
                }
            }
        }

        stage("deploy jar module") {
            steps {
                script {
                    deploy 'common'
                }
            }
        }


    }
}